[celestica]: Add dx010 gpio sysfs exported when platform modules load.
Signed-off-by: Guohan Lu <gulv@microsoft.com>

diff --git a/platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init b/platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
--- a/platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
+++ b/platform/broadcom/sonic-platform-modules-cel/debian/platform-modules-dx010.init
@@ -11,6 +11,24 @@
 # Short-Description: Setup DX010 board.
 ### END INIT INFO
 
+function export_gpio {
+label=$2
+gpio_num=$1
+gpio_base=`( cat /sys/class/gpio/gpiochip*/base | head -1 ) 2>/dev/null`
+gpio_label=`( cat /sys/class/gpio/gpiochip*/label | head -1 ) 2>/dev/null`
+if [[ "X$gpio_base" == "X" ]] ||
+( [[ "X$label" != "X" ]] && [[ "$label" != "$gpio_label" ]] ); then
+        echo "Platform driver error: No gpiochip found!"
+        exit 1;
+fi
+ionum=$((gpio_base+gpio_num))
+echo $ionum > /sys/class/gpio/export
+if [ $? -ne 0 ]; then
+        echo "Platform driver error: Cannot export gpio$ionum!"
+        exit 1;
+fi
+}
+
 case "$1" in
 start)
         echo -n "Setting up board... "
@@ -76,6 +94,29 @@ start)
 
         modprobe dx010_cpld
         sleep 2
+
+        # Export platform gpio sysfs
+        export_gpio 10  # Fan 1 present
+        export_gpio 11  # Fan 2 present
+        export_gpio 12  # Fan 3 present
+        export_gpio 13  # Fan 4 present
+        export_gpio 14  # Fan 5 present
+
+        export_gpio 22  # PSU L PWOK
+        export_gpio 25  # PSU R PWOK
+        export_gpio 27  # PSU L ABS
+        export_gpio 28  # PSU R ABS
+
+        export_gpio 29  # Fan 1 LED: Red
+        export_gpio 30  # Fan 1 LED: Yellow
+        export_gpio 31  # Fan 2 LED: Red
+        export_gpio 32  # Fan 2 LED: Yellow
+        export_gpio 33  # Fan 3 LED: Red
+        export_gpio 34  # Fan 3 LED: Yellow
+        export_gpio 35  # Fan 4 LED: Red
+        export_gpio 36  # Fan 4 LED: Yellow
+        export_gpio 37  # Fan 5 LED: Red
+        export_gpio 38  # Fan 5 LED: Yellow
 
         # Turn off/down lpmod by defult (0 - Normal, 1 - Low Pow)
         echo 0x00000000 > /sys/devices/platform/dx010_cpld/qsfp_lpmode
