[docker-base]: Build supervisor package from source in order to update to v3.3.2 (#777)
- Resolves issue #762

diff --git a/dockers/docker-base/Dockerfile.j2 b/dockers/docker-base/Dockerfile.j2
--- a/dockers/docker-base/Dockerfile.j2
+++ b/dockers/docker-base/Dockerfile.j2
@@ -1,8 +1,9 @@
 FROM debian:jessie
 
-## Clean documentation in FROM image
+# Clean documentation in FROM image
 RUN find /usr/share/doc -depth \( -type f -o -type l \) ! -name copyright | xargs rm || true
-## Clean doc directories that are empty or only contain empty directories
+
+# Clean doc directories that are empty or only contain empty directories
 RUN while [ -n "$(find /usr/share/doc -depth -type d -empty -print -exec rmdir {} +)" ]; do :; done
 RUN rm -rf               \
     /usr/share/man/*     \
@@ -13,18 +14,17 @@ RUN rm -rf               \
     /var/cache/man/*     \
     /usr/share/locale/*
 
-## Make apt-get non-interactive
+# Make apt-get non-interactive
 ENV DEBIAN_FRONTEND=noninteractive
 
-## Configure data sources for apt/dpkg
+# Configure data sources for apt/dpkg
 COPY ["sources.list", "/etc/apt/sources.list"]
 COPY ["dpkg_01_drop", "/etc/dpkg/dpkg.cfg.d/01_drop"]
 RUN apt-get update
 
-## Pre-install fundamental packages
+# Pre-install fundamental packages
 RUN apt-get -y install \
     rsyslog            \
-    supervisor         \
     vim-tiny           \
     perl               \
     python             \
@@ -34,25 +34,45 @@ COPY ["etc/rsyslog.conf", "/etc/rsyslog.conf"]
 COPY ["etc/rsyslog.d/*", "/etc/rsyslog.d/"]
 COPY ["root/.vimrc", "/root/.vimrc"]
 
+# Install dependencies of supervisor
+RUN apt-get -y install python-pkg-resources python-meld3
+
+RUN mkdir -p /etc/supervisor
+RUN mkdir -p /var/log/supervisor
+
+COPY ["etc/supervisor/supervisord.conf", "/etc/supervisor/"]
+
 RUN apt-get -y purge   \
     exim4              \
     exim4-base         \
     exim4-config       \
     exim4-daemon-light
 
-{% if docker_base_dbgs %}
-## Install common debug-packages
-RUN apt-get -y install \
-{% for dbg_pkg in docker_base_dbgs.split(' ') -%}
-    {{ dbg_pkg }}{{' '}}
+{% if docker_base_debs.strip() -%}
+# Copy built Debian packages
+{%- for deb in docker_base_debs.split(' ') %}
+COPY debs/{{ deb }} debs/
+{%- endfor %}
+
+# Install built Debian packages and implicitly install their dependencies
+{%- for deb in docker_base_debs.split(' ') %}
+RUN dpkg_apt() { [ -f $1 ] && { dpkg -i $1 || apt-get -y install -f; } || return 1; }; dpkg_apt debs/{{ deb }}
+{%- endfor %}
+{%- endif %}
+
+{% if docker_base_dbgs.strip() -%}
+# Install common debug-packages
+{%- for dbg_pkg in docker_base_dbgs.split(' ') %}
+RUN apt-get -y install {{ dbg_pkg }}
 {%- endfor %}
 {% else %}
 RUN ln /usr/bin/vim.tiny /usr/bin/vim
-{% endif %}
+{%- endif %}
 
-## Clean up apt
-## Remove /var/lib/apt/lists/*, could be obsoleted for derived images
-RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y; \
-    rm -rf /var/lib/apt/lists/*;                                   \
-    rm -rf /tmp/*;
+# Clean up apt
+# Remove /var/lib/apt/lists/*, could be obsoleted for derived images
+RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
+RUN rm -rf /var/lib/apt/lists/*
+
+RUN rm -rf /tmp/*
 
