[devices]: DELL Platform 2.0 API Infra and Reboot Reason support in Z9100 & S6100 (#3063)

diff --git a/dockers/docker-platform-monitor/start.sh.j2 b/dockers/docker-platform-monitor/start.sh.j2
--- a/dockers/docker-platform-monitor/start.sh.j2
+++ b/dockers/docker-platform-monitor/start.sh.j2
@@ -37,6 +37,24 @@ if [ -e /usr/share/sonic/platform/fancontrol ]; then
     supervisorctl start fancontrol
 fi
 
+
+# If the sonic-platform package is not installed, try to install it
+pip show sonic-platform > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    SONIC_PLATFORM_WHEEL="/usr/share/sonic/platform/sonic_platform-1.0-py2-none-any.whl"
+    echo "sonic-platform package not installed, attempting to install..."
+    if [ -e ${SONIC_PLATFORM_WHEEL} ]; then
+       pip install ${SONIC_PLATFORM_WHEEL}
+       if [ $? -eq 0 ]; then
+          echo "Successfully installed ${SONIC_PLATFORM_WHEEL}"
+       else
+          echo "Error: Failed to install ${SONIC_PLATFORM_WHEEL}"
+       fi
+    else
+       echo "Error: Unable to locate ${SONIC_PLATFORM_WHEEL}"
+    fi
+fi
+
 {% if not skip_ledd %}
 supervisorctl start ledd
 {% endif %}
