[LLDP] Add lldpmgrd Daemon to Manage LLDP Configuration (#1428)

diff --git a/dockers/docker-lldp-sv2/Dockerfile.j2 b/dockers/docker-lldp-sv2/Dockerfile.j2
--- a/dockers/docker-lldp-sv2/Dockerfile.j2
+++ b/dockers/docker-lldp-sv2/Dockerfile.j2
@@ -1,37 +1,49 @@
 FROM docker-config-engine
 
-COPY \
-{% for deb in docker_lldp_sv2_debs.split(' ') -%}
-debs/{{ deb }}{{' '}}
-{%- endfor -%}
-debs/
-
-COPY python-wheels /python-wheels
-
-## Make apt-get non-interactive
+# Make apt-get non-interactive
 ENV DEBIAN_FRONTEND=noninteractive
 
-RUN apt-get update && apt-get install -y python-pip libbsd0 libevent-2.0-5 libjansson4 libwrap0 libxml2 libpci3 libperl5.20 
+# Update apt's cache of available packages
+RUN apt-get update
 
-# Pre-install the fundamental packages
-# Install Python SwSS SDK
-# Install LLDP Sync Daemon
+# Install dependencies
+RUN apt-get install -y python-pip libbsd0 libevent-2.0-5 libjansson4 libwrap0 libxml2 libpci3 libperl5.20 libpython2.7
 
-RUN dpkg -i \
-{% for deb in docker_lldp_sv2_debs.split(' ') -%}
-debs/{{ deb }}{{' '}}
+{% if docker_lldp_sv2_debs.strip() -%}
+# Copy locally-built Debian package dependencies
+{%- for deb in docker_lldp_sv2_debs.split(' ') %}
+COPY debs/{{ deb }} /debs/
 {%- endfor %}
 
-RUN pip install /python-wheels/swsssdk-2.0.1-py2-none-any.whl && \
-    pip install /python-wheels/sonic_d-2.0.0-py2-none-any.whl && \
-    apt-get remove -y python-pip && \
-    apt-get purge -y && apt-get autoclean -y && apt-get autoremove -y && \
-    rm -rf /debs /python-wheels ~/.cache
+# Install locally-built Debian packages and implicitly install their dependencies
+{%- for deb in docker_lldp_sv2_debs.split(' ') %}
+RUN dpkg_apt() { [ -f $1 ] && { dpkg -i $1 || apt-get -y install -f; } || return 1; }; dpkg_apt /debs/{{ deb }}
+{%- endfor %}
+{%- endif %}
+
+{% if docker_lldp_sv2_whls.strip() -%}
+# Copy locally-built Python wheel dependencies
+{%- for whl in docker_lldp_sv2_whls.split(' ') %}
+COPY python-wheels/{{ whl }} /python-wheels/
+{%- endfor %}
+
+# Install locally-built Python wheel dependencies
+{%- for whl in docker_lldp_sv2_whls.split(' ') %}
+RUN pip install /python-wheels/{{ whl }}
+{%- endfor %}
+{% endif %}
+
+# Clean up
+RUN apt-get remove -y python-pip
+RUN apt-get clean -y
+RUN apt-get autoclean -y
+RUN apt-get autoremove -y
+RUN rm -rf /debs /python-wheels ~/.cache
 
 COPY ["start.sh", "/usr/bin/"]
 COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
-COPY ["reconfigure.sh", "/usr/bin/"]
 COPY ["lldpd.conf.j2", "/usr/share/sonic/templates/"]
 COPY ["lldpd", "/etc/default/"]
+COPY ["lldpmgrd", "/usr/bin/"]
 
 ENTRYPOINT ["/usr/bin/supervisord"]
